name: nuget release

on: 
  push:
    branches: 
      - master
    paths: 
      - src/AdaptiveCardMaker/AdaptiveCardMaker.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/AdaptiveCardMaker/AdaptiveCardMaker.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore src/AdaptiveCardMaker/AdaptiveCardMaker.csproj
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Publish AdaptiveCardMaker
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/AdaptiveCardMaker/AdaptiveCardMaker.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
